### ISSUE TITLE
Save As - Save a file as a different name

### ISSUE THREAD

**Issue by phated** [parallaxinc/Parallax-IDE#152]
Split out from #108

**Comment by spatializes** [comment]
@PropGit when Save As is triggered, what would you like to show in the filename box?  Currently it will show the active file name (see image below for file "a test"). Does that work?  Or would you like it to show "activeFilename copy"? Or "activeFilename1"? Or continue on with the "untitled#" scheme? Something else?

![image](https://cloud.githubusercontent.com/assets/2586086/8341999/f084d5c2-1a7d-11e5-9c6a-cc50fcd6de2d.png)

**Comment by jeffam70** [comment]
@drquinn Thanks for asking.  Since the common workflow is for someone to want to _save as_ to a similar (but different) name, I'd like to to show the active name (as you now have it) with the field focused and with the cursor to the right of the name.

Also, this reminds me of a needed feature... When the user clicks the _Save As_ button from this overlay, the Save As feature should always prompt with a confirmation if the user uses a filename that already exists (ie: "File '<filename>' already exists.  Overwrite anyway?" with _Overwrite_ and _Cancel_ button options).

I can make that a separate linked issue if you want.

**Comment by spatializes** [comment]
@jeffam70 ok great, I'll set that up for filename.

I think another issue would be good for the overwrite prompt and dialog that would go along with it.

**Comment by PropGit** [comment]
Tested, but the cursor doesn't end up to the right of the filename.  Will make another issue for this.
