### ISSUE TITLE
File System Error - new unsaved file lost between sessions

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#208]
[This happened twice.  May have to do with speed of operations.]
- Created a new file
- Typed some text
- Closed Parallax IDE
- Started Parallax IDE
  - Error... file lost (see image)
    ![image](https://cloud.githubusercontent.com/assets/1266318/8920707/7fa466ba-3481-11e5-81b3-bf26c47b4b43.png)

**Comment by PropGit** [comment]
Just retried.  It's possible to make changes in a new file, close Parallax IDE, start Parallax IDE and that file is lost (sometimes without visible error; just a different file in the view instead of the last file from last session).

Can you put a trap upon Parallax IDE close event that causes it to finish storing any unstored changes before fully closing down?

**Comment by phated** [comment]
Much of this was probably a side effect of the bad filesystem implementation.  I believe it should get better after this sprint, but might not be completely resolved.

Unfortunately, there is no way to implement a trap in the editor unless **ALL** filesystem operations were deferred to the background page (and I'm not sure if the background page has that access) which would be incredibly inefficient for the editor due to message passing serialization.  Background pages are the only thing guaranteed to be running and able to catch a close event initiated from exiting the application.

**Comment by PropGit** [comment]
Verified that this seems to be fixed.  It was not a definitive problem (occurred at random) but I haven't seen it happen through extensive tests in v0.7.1 now.
