### ISSUE TITLE
Communicate to the BASIC Stamp 2 over USB serial connection.

### ISSUE THREAD

**Issue by phated** [parallaxinc/Parallax-IDE#47]
Mainly just receiving of `DEBUG` statements for this phase.

**Comment by PropGit** [comment]
Here's some implementation notes.  Items _not_ required for proof-of-concept are marked **FUTURE**, and are included here only as a "heads up" about later needs.

The data is standard RS-232-like asynchronous serial data.  
- For "DEBUG" data, it is 8-bit, no parity, 1 stop bit (8, N, 1)
  - For BS2, BS2e, BS2sx, BS2p, and BS2pe, it is transmitted at 9,600 baud
  - **FUTURE:** For BS2px, "DEBUG" data is transmitted at 19,200 baud.
- **FUTURE:** For "SEROUT" data, in addition to the above, it can be (7, E, 1) and various baud rates from 300 to 38,400.
- **FUTURE:** Propeller 1 can transmit at up to 3 MBaud.

The process is:
- If downloaded PBASIC Image contains a DEBUG statement, ensure that serial terminal display is visible and ready to receive data immediately after download
  - Do not close the serial port between downloading and serial terminal activation
- Monitor serial receive buffer for any incoming data
  - The desired method for this is _event driven_ rather than _polled_ since polling takes extra processing time and results in jerky display response that is ugly
    See issue #48 for more info.
