### ISSUE TITLE
PBASIC Syntax Highlighting

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#85]
Add PBASIC Syntax Highlighting as described in [Issue 71](https://github.com/parallaxinc/ChromeIDE/issues/71).

NOTE: True PBASIC Syntax highlighting also changes the case of the symbols in the source code, and also causes those changes to be saved in the file (as if entered that way by the user).  Since that is probably beyond what is readily available in the Chrome IDE edit control, we will gladly defer the case-modification feature for now and just request highlight and style adjustment.

**Comment by monteslu** [comment]
@PropGit got the first pass at recognizing all the reserved words, handling indentation correctly in if-elseif-endif, do-while blocks, etc.  As well as correctly recognizing comment blocks.

![syntax](https://cloud.githubusercontent.com/assets/423800/7691126/e8ee5aa0-fd6c-11e4-852a-0225583e2dd2.png)

I could use some advice on matching the colors described in #71 to hex colors so that we can update the styles in codemirror.  Is it possible for you to match the colors in the attached screenshot to what they need to be?

**Comment by PropGit** [comment]
@monteslu and @drquinn I'm not positive I know what advice you need, but I just posted more clear syntax metrics in post# 5 of Issue #71. 

In the colored example you provided,
- the `Rnd`, `LED1`, and `GetRandom:` are a user-defined symbols, they don't match any reserved words, so the SynDefault gets applied (black font on white background, plain font style, no case change).
- `VAR` and `PIN` are SynDeclaration.
- `Word` is a SynVariableType.
- `0`, `100`, `999`, and `1` are SynConstantDecimal.
- `DO`, `GOSUB`, `HIGH`, `PAUSE`, `LOW`, `LOOP`, `RANDOM`, and `RETURN` are SynCommand.
- `=` is SynConditionalOp.
- `//`, and `+` are SynBinaryOp.

**Comment by PropGit** [comment]
Verified all reserved words are syntax highlighted correctly, except DEBUGIN... this is because I mistakenly labeled it as an etConstant.
